const INIT_DATA ="INIT_DATA"
const CREATE_HOBIT ="CREATE_HOBIT"
const ADD_HOBIT ="ADD_HOBIT"
const COMPLETE_HOBIT ="COMPLETE_HOBIT"
export{
  INIT_DATA,
  CREATE_HOBIT,
  ADD_HOBIT,
  COMPLETE_HOBIT
}